### ISSUE TITLE
Markers appear vertically offset

### ISSUE THREAD

**Issue by perliedman** [jacobtoye/Leaflet.iconlabel#5]
When adding more than one marker, the markers appear more and more vertically offset from the actual marker coordinate. This affects only the marker image, the shadow still appears in the correct location.

I have made Gist that illustrates the example, that adds ten markers to the exact same location: https://gist.github.com/3665685

This is an illustration of how this renders in my browser:

![Issue screenshot](http://www.liedman.net/share/leaflet.iconlabel-issue.png)

Haven't used Leaflet.iconlabel before, so I might have made some stupid mistake, but I can't see anything wrong with the code.

**Comment by JohnHanks** [comment]
this appears to be a bug still not fixed in leaflet vanilla

**Comment by perliedman** [comment]
@JohnHanks that sounds weird, given that it was fixed more than three years ago. Maybe you're seeing a different but similar issue?

Can you provide a jsfiddle or similar to illustrate the problem?

**Comment by geirsagberg** [comment]
I had the same issue of icons getting vertical offsets. Turns out my problem was I was using `L.divIcon` without `position: absolute`. As soon as I added absolute positioning to the div markers, they all were placed correctly.

**Comment by veratechnz** [comment]
@geirsagberg
You are a legend sir!

**Comment by IanMayo** [comment]
Thank goodness for the fix in this issue. I'm not using `Leaflet.iconLabel`, but was still experiencing this issue.

Find the correct place to apply `position: absolute` saved the day!

Thanks @jacobtoye 😃
